### ISSUE TITLE
FC-014: 設定ファイル実装 - config.toml統合管理システム

### ISSUE THREAD

**Issue by biwakonbu** [biwakonbu/fcode#27]
## 背景
現在のfcodeは設定がハードコーディングされており、ユーザーカスタマイズができません。`~/.config/claude-tui/config.toml`による設定管理システムを実装し、柔軟な設定変更を可能にします。

## 目的
1. TOML形式の設定ファイルシステムを実装する
2. Claude CLI パス・ペイン設定・キーバインドのカスタマイズを可能にする
3. 環境変数との統合および設定階層の管理を実現する

## 作業内容
- [ ] **ConfigManager実装**: TOML設定ファイルの読み書き機能
- [ ] **設定スキーマ定義**: デフォルト設定・バリデーション機能
- [ ] **初回起動時設定生成**: `~/.config/claude-tui/config.toml`自動作成
- [ ] **実行時設定変更**: 設定変更とファイル保存機能
- [ ] **環境変数統合**: CLAUDE_API_KEY等の自動検出・優先制御
- [ ] **設定階層管理**: グローバル・プロジェクト・ユーザー設定の統合
- [ ] **マイグレーション**: 設定ファイルバージョン管理

## 受け入れ基準
- [ ] 初回起動時にデフォルト設定ファイルが自動生成される
- [ ] 設定変更が即座に反映され、ファイルに永続化される
- [ ] 不正な設定値でもフォールバック設定で動作が継続される
- [ ] 環境変数が設定ファイルより優先される
- [ ] 設定診断機能で問題箇所が自動特定される

## 設定ファイル構造

```toml
[general]
version = "1.0.0"
auto_save_interval_ms = 30000
log_level = "INFO"

[claude]
cli_path = "/usr/local/bin/claude"
api_key_env = "CLAUDE_API_KEY"
default_model = "claude-3-5-sonnet-20241022"

[ui]
theme = "solarized"
auto_start_panes = ["dev1", "qa1"]
pane_startup_delay_ms = 500

[keybindings]
exit = "Ctrl+X Ctrl+C"
next_pane = "Ctrl+X O"
help = "Ctrl+X H"

[panes.dev1]
auto_start = true
working_directory = "."
environment_variables = { CLAUDE_ROLE = "dev" }

[panes.qa1]
auto_start = true
working_directory = "."
environment_variables = { CLAUDE_ROLE = "qa" }

[resources]
max_memory_mb = 512
max_cpu_percent = 50
max_sessions = 7
```

### 1. ConfigManager
```fsharp
type Config = {
    General: GeneralConfig
    Claude: ClaudeConfig
    UI: UIConfig
    KeyBindings: KeyBindingsConfig
    Panes: Map<string, PaneConfig>
    Resources: ResourceConfig
}

type ConfigManager() =
    member _.LoadConfig: unit -> Config
    member _.SaveConfig: Config -> unit
    member _.ValidateConfig: Config -> ValidationResult
    member _.MigrateConfig: string -> Config
```

### 2. 設定階層
- **デフォルト設定**: アプリケーション組み込み
- **グローバル設定**: `~/.config/claude-tui/config.toml`
- **プロジェクト設定**: `./.claude-tui/config.toml`
- **環境変数**: 最高優先度

### 3. 診断機能
- Claude CLI の動作確認
- 権限・パス設定の検証
- 問題箇所の自動特定とレポート

## リソース設計
- **ディスク使用量**: 設定ファイル1-10KB想定
- **CPU負荷**: 設定読み込みで+0.1%想定
- **メモリ使用量**: 設定管理で+5-10MB想定

## 参照
- TODO.md セクション 5.1 (設定・構成管理)
- `docs/process-architecture.md` - 設定統合設計

---
**見積**: 1 人日
**優先度**: 🟨 中
**依存**: FC-013完了

🤖 Generated with [Claude Code](https://claude.ai/code)
