### ISSUE TITLE
FC-015: 統合テストスイート実装 - Claude統合・UI自動操作・性能回帰テスト

### ISSUE THREAD

**Issue by biwakonbu** [biwakonbu/fcode#28]
## 背景
現在のテストスイートは単体テストが中心で、Claude Code統合やUI操作の自動テストが不足しています。CI/CD環境での包括的な品質保証を実現するため、統合テストスイートを実装します。

## 目的
1. Claude Code統合の自動テスト機能を実装する
2. UI操作の自動化テスト機能を提供する
3. 性能回帰テストによる継続的品質保証を実現する

## 作業内容
- [ ] **Claude統合テスト**: 実際のClaude Code プロセスとの統合テスト
- [ ] **UI自動操作テスト**: キーバインド・ペイン操作の自動化テスト
- [ ] **性能回帰テスト**: レスポンス時間・メモリ使用量のベンチマーク
- [ ] **E2Eシナリオテスト**: 典型的な使用パターンの自動実行
- [ ] **並行処理テスト**: 複数ペイン同時実行での安定性テスト
- [ ] **CI/CD統合**: GitHub Actions での自動テスト実行
- [ ] **テストレポート**: カバレッジ・性能データの可視化

## 受け入れ基準
- [ ] Claude Code統合テストがCI環境で安定実行される
- [ ] UI操作テストで全キーバインドが検証される
- [ ] 性能回帰テストで閾値超過が自動検出される
- [ ] E2Eテストで典型的なワークフローが自動化される
- [ ] テストレポートで品質トレンドが可視化される

### 1. Claude統合テスト
```fsharp
[<Test>]
let ``Claude Code Integration Test`` () =
    // Mock Claude Code プロセス起動
    // 入力→応答サイクルの検証
    // セッション状態の正常性確認
```

### 2. UI自動操作テスト
```fsharp
[<Test>]
let ``UI Automation Test`` () =
    // 仮想キーイベント生成
    // ペイン切り替え動作検証
    // TextView更新確認
```

### 3. 性能回帰テスト
```fsharp
[<Test>]
let ``Performance Regression Test`` () =
    // ベースライン性能との比較
    // メモリリーク検出
    // レスポンス時間測定
```

### 4. テストカテゴリ拡張
- **Unit**: 既存の単体テスト (82テスト)
- **Integration**: Claude統合・プロセス間通信テスト
- **Performance**: 性能・リソース使用量テスト
- **E2E**: エンドツーエンドシナリオテスト
- **UI**: ユーザーインターフェース自動操作テスト

### 5. CI/CD統合
```yaml
- name: Run Integration Tests
  run: dotnet test --filter "TestCategory=Integration"
  
- name: Run Performance Tests  
  run: dotnet test --filter "TestCategory=Performance"
  
- name: Generate Test Report
  run: dotnet test --collect:"XPlat Code Coverage"
```

## テスト環境設計
- **Mock Claude Code**: テスト用のダミープロセス
- **仮想ターミナル**: UI操作テスト用の仮想環境
- **ベンチマークデータ**: 性能基準値の管理
- **自動レポート**: テスト結果の継続的監視

## リソース設計
- **テスト実行時間**: 5-10分想定 (CI環境)
- **CPU負荷**: テスト実行時+20-30%想定
- **メモリ使用量**: テスト環境で+200-300MB想定

## 参照
- TODO.md セクション 5.2 (テスト・品質保証強化)
- `.github/workflows/ci.yml` - CI設定
- `tests/` - 既存テストスイート

---
**見積**: 2 人日
**優先度**: 🟨 中
**依存**: FC-014完了

🤖 Generated with [Claude Code](https://claude.ai/code)
